name: ESLint

on:
  push:
    branches: [ master-branch ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master-branch ]
  schedule:
    - cron: '41 9 * * 3'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: npm install

      - name: Run ESLint
        run: make lint
        continue-on-error: true
